version: "3.9"
services:
 
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
      POSTGRES_DB: core_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./main_module/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

  main_module:
    build: ./main_module
    env_file:
      - ./main_module/.env
    ports:
      - "18080:18080"
    depends_on:
      - postgres
    networks:
      - app_net

networks:
  app_net:

volumes:
  pgdata:
